({
    defaultAvatar: "https://www.teenwiseseattle.com/wp-content/uploads/2017/04/default_avatar.png",
    TOKEN: require("./token.json"),
    sendingChanceCoefficient: function() {
        var now = new Date();
        if(now.getMonth() == 3 && now.getDate() == 1) return 1;
        else return 0.001;
    },
    percentMatchedWordsMax: 10,
    cooldown: function() {
        return 1000 * 60 * 5;
    },
    categoryWakeWords() {
        var wakeWords = {
            age: ["old", "young", /\d+ years old/i, "aged", "older", "birthday"],
            car: ["engine", "subie", "car", "subaru", "toyota", "ford", "vroom", "drive", "tesla", "driver"],
            education: ["school", "learning", "college", "smart", "grades?", "essays?"],
            forgiveness: ["forgive"],
            health: ["healthy", "prescription", "unhealthy"],
            legal: ["law", "lawyer", "court", "legally"],
            music: ["song", "tune", "notes", "sing", "instrument", "musical", "ballet", "opera", "ballroom dance"],
            religion: ["jesus", "bible", "biblical", "christianity", "islam", "islamic", "muslim", "jew", "jewish", "christian", "crucifix"],
            technology: ["tesla", "tech", "coding", "program", "programmed", "bot", "programming","artificial intelligence", "ai"],
            alone: ["lonely", /(all by|on) (my|their|hi[sm]|her) ?(self|own)/i],
            environmental: ["tree", "vegetarian", "global warming", "climate change", "plants", "plant", "the earth is heating up"],
            freedom: ["liberty", "free", "unchained", "freed"],
            history: ["historical", "world war", "the past", /\bww ?(\d+|iii+)/i],
            life: ["living"],
            nature: ["trees", "mother nature", ""],
            respect: [/(\w+ )?sucks?/i, "respectful"],
            teen: [/(\b1[3-9]\b[- ]y)|(freshm[ae]n)/i, "procrastinate", "procrastination", "minecraft"],
            amazing: ["amazed"],
            communication: ["talk", "talking", "communicate"],
            equality: ["the same"],
            // friendship: [],
             home: ["house", "houses"],
            // love: [],
            // parenting: [],
            // romantic: [],
            // thankful: [],
            anger: ["angry", "angy", "mad", "malding", "rage", "raging", "irritated", "ticked off", "pissed off"],
            // computers: [],
            // experience: [],
            // funny: [],
            // hope: [],
            // marriage: [],
            // patience: [],
            sad: ["hate"],
            // time: [],
            // anniversary: [],
            // cool: [],
            // failure: [],
            // future: [],
            // humor: [],
            // medical: [],
            // patriotism: [],
            // science: [],
            // travel: [],
            // architecture: [],
            // courage: [],
            // faith: [],
            // gardening: [],
            // imagination: [],
            men: ["mankind", "man"],
            // peace: [],
            // smile: [],
            // trust: [],
            // art: [],
            // dad: [],
            // family: [],
            // god: [],
            // inspirational: [],
            // mom: [],
            // pet: [],
            // society: [],
            // truth: [],
            // attitude: [],
            // dating: [],
            // famous: [],
            // good: [],
            // intelligence: [],
            // money: [],
            // poetry: [],
            // sports: [],
            // war: [],
            // beauty: [],
            // death: [],
            // fear: [],
            // government: [],
            // jealousy: [],
            // morning: [],
            // politics: [],
            // strength: [],
            wedding: [/marry/],
            // best: [],
            // design: [],
            // finance: [],
            // graduation: [],
            // knowledge: [],
            // motivational: [],
            // positive: [],
            // success: [],
            // birthday: [],
            // diet: [],
            // fitness: [],
            // great: [],
            // leadership: [],
            // movies: [],
            // power: [],
            // sympathy: [],
            // business: [],
            dreams: ["dreamed", "dream"],
            food: ["hamburger", "breakfast", "lunch", "dinner"],
            happiness: ["happy"],
            learning: ["Learn"],
            // movingon: [],
            // relationship: [],
            teacher: ["teach"],
        
        };
        return Object.entries(wakeWords).map(x=>[x[0],x[1].map(y=>{
            if(typeof y == "string") return new RegExp("\\b" + y + "\\b", "i");
            else return y; 
        })]);
    }
})